"type: ci":
  - .github/workflows/**
  - .husky/**

"type: docker":
  - "**/Dockerfile"
  - "docker-compose.yml"

"app: api":
  - apps/api/**

"app: marketing":
  - apps/marketing/**

"app: web-client":
  - apps/web-client/**

"app: url-shortener":
  - apps/trpk.it/**

"package: kms":
  - packages/kms/**

"package: storage":
  - packages/storage/**

"package: tracker":
  - packages/tracker-crypto/**
  - packages/tracker-script/**