"type: ci":
  - .github/workflows/**
  - .husky/**

"type: docker":
  - "**/Dockerfile"
  - "docker-compose.yml"

"app: marketing":
  - apps/marketing/**

"app: web-client":
  - apps/web-client/**

"package: kms":
  - packages/kms/**

"package: storage":
  - packages/storage/**