"type: ci":
  - .github/workflows/**
  - .husky/**

"type: docker":
  - "**/Dockerfile"
  - "docker-compose.yml"

"app: marketing":
  - apps/marketing/**

"app: web-client":
  - apps/web-client/**

"app: url-shortener":
  - apps/url-shortener/**

"package: common":
  - packages/common/**

"package: config":
  - packages/config/**
  - packages/tsconfig/**

"package: kms":
  - packages/kms/**

"package: storage":
  - packages/storage/**

"package: tracker":
  - packages/tracker-crypto/**
  - packages/tracker-script/**