import { base64url } from "@scure/base";
import { BoxKeyPair, SignKeyPair } from "tweetnacl";

const encoder = new TextEncoder();
const decoder = new TextDecoder();

/**
 * @param public - Formatted key with the public base64 encoded from the key pair.
 * @param secret - Formatted key with the secret base64 encoded from the key pair.
 */
export type NaclBaseKey = {
  public: string;
  secret: string;
};

/**
 * @param keyPair - A key pair generated by `nacl.box.keyPair()`.
 */
export type NaclBoxKey = NaclBaseKey & {
  keyPair: BoxKeyPair;
};

/**
 * @param keyPair - A key pair generated by `nacl.sign.keyPair()`.
 */
export type NaclSignatureKey = NaclBaseKey & {
  keyPair: SignKeyPair;
};

/**
 * @param input - The input string to parse.
 * @param regex - The regular expression to use to parse the input string.
 */
export function parse(input: string, regex: RegExp): Uint8Array {
  const match = input.match(regex);
  if (!match) {
    throw new Error("invalid input");
  }

  return base64url.decode(input);
}

/**
 * @param input - The input string to encode.
 */
export function utf8Encode(input: string): Uint8Array {
  return encoder.encode(input);
}

/**
 * @param input - The input buffer to decode.
 */
export function utf8Decode(input: Uint8Array): string {
  return decoder.decode(input);
}
