name: 'Bug report'
description: "Report something that's broken"
body:
  - type: markdown
    attributes:
      value: "Please read our [contribution guide](https://github.com/trpkit/trpkit/blob/main/.github/CONTRIBUTING.md) before submitting bug reports."
  - type: textarea
    attributes:
      label: Description
      description: Provide a detailed description of the issue you are facing.
    validations:
      required: true