#!/usr/bin/env bash

cd "$(dirname "$0")/.." || exit
rootDir=$(pwd)

echo -e "ATTENTION: The files being accessed through this script are subject to different licensing terms than the rest of the project. By proceeding, you acknowledge that you have reviewed and accepted these terms.\n\nIf you are not familiar with these terms, please review them before continuing.\n\nDo you wish to continue? (Y/Yes to accept and proceed, any other key to abort)"
read -r answer

if [[ ! $answer =~ ^[Yy](es)?$ ]]; then
  echo "License declined. Aborting..."
  exit 1
fi

if ! command -v git &> /dev/null; then
  echo "Git is not installed"
  exit 1
fi

if ! command -v rustc &> /dev/null; then
  echo "Rust is not installed"
  exit 1
fi

# Check if repository is already cloned
if [ -d "$rootDir/tmp/opaque-wasm/.git" ]; then
  git -C "$rootDir/tmp/opaque-wasm" pull
else
  git clone https://github.com/marucjmar/opaque-wasm.git "$rootDir/tmp/opaque-wasm"
fi

# Build server
wasm-pack build --out-dir "$rootDir/autogenerated/opaque-server" --out-name opaque-server --release --target nodejs "$rootDir/tmp/opaque-wasm"
if [ $? -ne 0 ]; then
  echo "Failed to build opaque server"
  exit 1
fi

# Build client
wasm-pack build --out-dir "$rootDir/autogenerated/opaque-client" --out-name opaque-client --release --target web "$rootDir/tmp/opaque-wasm" --no-default-features --features client
if [ $? -ne 0 ]; then
    echo "Failed to build opaque client"
    exit 1
fi

# Patch server
cd "$rootDir/autogenerated/opaque-server" || exit
pnpm pkg set name=@trpkit/opaque-server
rm -rf .gitignore
echo "Opaque server patched successfully"

# Patch client
cd "$rootDir/autogenerated/opaque-client" || exit
pnpm pkg set name=@trpkit/opaque-client
rm -rf .gitignore
echo "Opaque client patched successfully"