name: Publish

on:
  push:
    tags: [ "*.*.*" ]

env:
  HUSKY: 0

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Log into Azure
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build and push accounts.trpkit.com
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./apps/accounts.trpkit.com/Dockerfile
          tags: ${{ secrets.ACR_REGISTRY }}/apps/accounts-trpkit-com:latest
      - name: Build and push mta-sts.trpkit.com app
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./apps/mta-sts.trpkit.com/Dockerfile
          tags: ${{ secrets.ACR_REGISTRY }}/apps/mts-sts-trpkit-com:latest
      - name: Build and push trpkit.com app
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./apps/trpkit.com/Dockerfile
          tags: ${{ secrets.ACR_REGISTRY }}/apps/trpkit-com:latest