name: Publish

on:
  push:
    tags: [ "*.*.*" ]

env:
  HUSKY: 0

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Log into Azure
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build and push marketing app
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./apps/marketing/Dockerfile
          tags: ${{ secrets.ACR_REGISTRY }}/marketing:latest
      - name: Build and push webclient app
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./apps/web-client/Dockerfile
          tags: ${{ secrets.ACR_REGISTRY }}/webclient:latest