name: Semgrep OSS Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ opened, synchronize ]

jobs:
  semgrep:
    name: semgrep-oss/scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4
      - run: semgrep scan --config auto