name: Semgrep OSS Scan

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches: ['main']

jobs:
  semgrep:
    name: semgrep-oss/scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4
      - run: semgrep scan --config auto